### ISSUE TITLE
vendor.qti.hardware.display.composer crashing prevents device boot.

### ISSUE THREAD

**Issue by Howarddj** [XperiaBrickers/device_sony_pdx206#2]
Tried to bring up lineage 19.1 trees to build ArrowOS 12.1.

Build successful but boot fails due to vendor.qti.hardware.display.composer crashing.

successfully tested boot, dtbo, vbmeta, vbmeta_system, recovery images by flashing over stock firmware and systems boots with no issues. 

error is somewhere in system, product or vendor img. 

has anyone managed to get Lineage 19.1 booted using these trees yet?

i can provide a log file if requested, 
thanks for the great work!

**Comment by SpectreDev-007** [comment]
Thanks for letting us know, if you could provide logs that would be great

**Comment by lolipuru** [comment]
> Tried to bring up lineage 19.1 trees to build ArrowOS 12.1.
> 
> Build successful but boot fails due to vendor.qti.hardware.display.composer crashing.
> 
> successfully tested boot, dtbo, vbmeta, vbmeta_system, recovery images by flashing over stock firmware and systems boots with no issues.
> 
> error is somewhere in system, product or vendor img.
> 
> has anyone managed to get Lineage 19.1 booted using these trees yet?
> 
> i can provide a log file if requested, thanks for the great work!

give me logcat then i'll look for it

**Comment by Howarddj** [comment]
SOLVED:

sorry guys, there was nothing wrong with the device trees. problem was in ROM repo. resync has fixed it. 

rebuilt ROM and device has booted absolutely fine. just working on 120hz fix now. 

this issue can be closed now.

**Comment by SpectreDev-007** [comment]
> SOLVED:
> 
> sorry guys, there was nothing wrong with the device trees. problem was in ROM repo. resync has fixed it.
> 
> rebuilt ROM and device has booted absolutely fine. just working on 120hz fix now.
> 
> this issue can be closed now.

120hz just requires an overlay, if you can, you can make a pull request and we will accept your arrow os trees and 120hz fix
