### ISSUE TITLE
fixed 120hz.

### ISSUE THREAD

**Issue by Howarddj** [XperiaBrickers/device_sony_pdx206#3]
https://review.lineageos.org/c/LineageOS/android_device_oneplus_sm8250-common/+/325408/

(ignore overlay-lineage folder modification, just include the other two. Edit default refresh rate from 0 to 60.)

including this commit in device tree fixes swapping between 60hz and 120hz display mode.

![Screenshot_20220817-220815_Settings Suggestions](https://user-images.githubusercontent.com/66848380/185243919-bccc670a-454b-40ad-8b3c-57e8a0fa9525.png)

![Screenshot_20220817-220832_Settings](https://user-images.githubusercontent.com/66848380/185244002-6cc6f443-4a71-4ab5-80f4-9964efb27caf.png)

![Screenshot_20220817-220849_Settings](https://user-images.githubusercontent.com/66848380/185244030-2847274c-1e9e-4055-868f-d96e07cd7606.png)

![Screenshot_20220817-220854_Settings](https://user-images.githubusercontent.com/66848380/185244048-1a052bfc-962b-4230-84d6-709a2129bf15.png)

developer options must be activated in rom to access option in settings.
tested working on ArrowOS 12.1

**Comment by Howarddj** [comment]
Sorry I didn't see your last comment on my previous closed thread, I'll try to work out a pull request as you suggested.

Thanks.

**Comment by SpectreDev-007** [comment]
its ok, im working on A13 trees now

**Comment by SpectreDev-007** [comment]
> Sorry I didn't see your last comment on my previous closed thread, I'll try to work out a pull request as you suggested.
> 
> Thanks.

Btw we can have better communication over telegram, my username on telegram is SpectreDev
